apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deploymentName }}
  labels:
    app: {{ .Values.api.label }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.label }}
    spec:
      containers:
      - name: {{ .Values.api.deploymentName }}
        image: {{ .Values.api.image.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        ports:
        - containerPort: {{ .Values.api.port }}
