apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
  labels:
    app: {{ .Values.api.label }}
spec:
  selector:
    app: {{ .Values.api.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}

