apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service }}
  labels:
    app: {{ .Values.ui.service }}  
spec:
  selector:
    app: {{ .Values.ui.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
