api:
  deploymentName: "api-deployment"
  label: "api"
  replicas: "2"
  image:
    registry: "kevalohith"
    repository: "api"
    tag: "v4"
  port: "5005"
  serviceName: "api-service"
  ingressName: "api-ingress"
  path: "/api/"

ui:
  deploymentName: "ui-deployment"
  label: "ui"
  replicas: "2"
  image:
    registry: "kevalohith"
    repository: "ui"
    tag: "v3"
  port: "3000"
  service: "ui-service"
  ingress: "reach-ingress"
  path: "/"
